baseurl = "http://jishu.io/"
languageCode = "en-us"
title = "极术"
theme = "hyde"

[params]
description = "科学技术是第一生产力"

[[menu.main]]
    name = "Kubernetes"
    identifier = "kubernetes"
    url = "/kubernetes/"
